[project]
name = "data-platform-demos"
version = "0.1.0"
description = "Demonstration code for working with the NACC Data Platform"
requires-python = ">=3.12"
dependencies = [
    "flywheel-sdk>=20.0.0",
    "keyring>=25.0.0",
    "nacc-common@ https://github.com/naccdata/flywheel-gear-extensions/releases/download/nacc-common%2Fv3.1.0/nacc_common-3.1.0-py3-none-any.whl",
    "python-dotenv>=1.0.0",
]

[dependency-groups]
dev = [
    "hypothesis",
    "mypy",
    "pytest",
    "ruff",
]

[tool.ruff]
target-version = "py312"

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
check_untyped_defs = true

[[tool.mypy.overrides]]
module = "flywheel.*"
ignore_missing_imports = true
