docker_image(name='r-uploader',
             source='Dockerfile',
             dependencies=[
                 '//:requirements', 'demo/r-uploader/src/r/uploader:r-files',
                 'common/src/python:nacccommon'
             ],
             image_tags=['0.0.1', 'latest'])
